[package]
name = "cachey"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4"
tokio = { version = "1.32", features = ["fs", "rt-multi-thread", "macros"] }
serde = { version = "1.0", features = ["derive"] }