name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: target/release/cachey
            asset_name: cachey-linux-amd64
          - os: windows-latest
            artifact_name: target/release/cachey.exe
            asset_name: cachey-windows-amd64.exe
          - os: macos-latest
            artifact_name: target/release/cachey
            asset_name: cachey-macos-amd64

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Build
      run: cargo build --release

    - name: Run tests
      run: cargo test --release

    - name: Rename binary
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          mv ${{ matrix.artifact_name }} ${{ matrix.asset_name }}
        else
          mv ${{ matrix.artifact_name }} ${{ matrix.asset_name }}
        fi
      shell: bash

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{ matrix.asset_name }}
